/**
 * generated by Xtext 2.12.0
 */
package edu.upb.lp.isc.pR.impl;

import edu.upb.lp.isc.pR.Accion;
import edu.upb.lp.isc.pR.PRPackage;
import edu.upb.lp.isc.pR.Variable;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Accion</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.pR.impl.AccionImpl#getOperador <em>Operador</em>}</li>
 *   <li>{@link edu.upb.lp.isc.pR.impl.AccionImpl#getObjeto1 <em>Objeto1</em>}</li>
 *   <li>{@link edu.upb.lp.isc.pR.impl.AccionImpl#getObjeto2 <em>Objeto2</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AccionImpl extends MinimalEObjectImpl.Container implements Accion
{
  /**
   * The default value of the '{@link #getOperador() <em>Operador</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperador()
   * @generated
   * @ordered
   */
  protected static final String OPERADOR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getOperador() <em>Operador</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperador()
   * @generated
   * @ordered
   */
  protected String operador = OPERADOR_EDEFAULT;

  /**
   * The cached value of the '{@link #getObjeto1() <em>Objeto1</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getObjeto1()
   * @generated
   * @ordered
   */
  protected Variable objeto1;

  /**
   * The cached value of the '{@link #getObjeto2() <em>Objeto2</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getObjeto2()
   * @generated
   * @ordered
   */
  protected Variable objeto2;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AccionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PRPackage.Literals.ACCION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getOperador()
  {
    return operador;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setOperador(String newOperador)
  {
    String oldOperador = operador;
    operador = newOperador;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PRPackage.ACCION__OPERADOR, oldOperador, operador));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Variable getObjeto1()
  {
    if (objeto1 != null && objeto1.eIsProxy())
    {
      InternalEObject oldObjeto1 = (InternalEObject)objeto1;
      objeto1 = (Variable)eResolveProxy(oldObjeto1);
      if (objeto1 != oldObjeto1)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, PRPackage.ACCION__OBJETO1, oldObjeto1, objeto1));
      }
    }
    return objeto1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Variable basicGetObjeto1()
  {
    return objeto1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setObjeto1(Variable newObjeto1)
  {
    Variable oldObjeto1 = objeto1;
    objeto1 = newObjeto1;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PRPackage.ACCION__OBJETO1, oldObjeto1, objeto1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Variable getObjeto2()
  {
    if (objeto2 != null && objeto2.eIsProxy())
    {
      InternalEObject oldObjeto2 = (InternalEObject)objeto2;
      objeto2 = (Variable)eResolveProxy(oldObjeto2);
      if (objeto2 != oldObjeto2)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, PRPackage.ACCION__OBJETO2, oldObjeto2, objeto2));
      }
    }
    return objeto2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Variable basicGetObjeto2()
  {
    return objeto2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setObjeto2(Variable newObjeto2)
  {
    Variable oldObjeto2 = objeto2;
    objeto2 = newObjeto2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PRPackage.ACCION__OBJETO2, oldObjeto2, objeto2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PRPackage.ACCION__OPERADOR:
        return getOperador();
      case PRPackage.ACCION__OBJETO1:
        if (resolve) return getObjeto1();
        return basicGetObjeto1();
      case PRPackage.ACCION__OBJETO2:
        if (resolve) return getObjeto2();
        return basicGetObjeto2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PRPackage.ACCION__OPERADOR:
        setOperador((String)newValue);
        return;
      case PRPackage.ACCION__OBJETO1:
        setObjeto1((Variable)newValue);
        return;
      case PRPackage.ACCION__OBJETO2:
        setObjeto2((Variable)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PRPackage.ACCION__OPERADOR:
        setOperador(OPERADOR_EDEFAULT);
        return;
      case PRPackage.ACCION__OBJETO1:
        setObjeto1((Variable)null);
        return;
      case PRPackage.ACCION__OBJETO2:
        setObjeto2((Variable)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PRPackage.ACCION__OPERADOR:
        return OPERADOR_EDEFAULT == null ? operador != null : !OPERADOR_EDEFAULT.equals(operador);
      case PRPackage.ACCION__OBJETO1:
        return objeto1 != null;
      case PRPackage.ACCION__OBJETO2:
        return objeto2 != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (operador: ");
    result.append(operador);
    result.append(')');
    return result.toString();
  }

} //AccionImpl
