/**
 * generated by Xtext 2.12.0
 */
package edu.upb.lp.isc.pR.impl;

import edu.upb.lp.isc.pR.Definicion;
import edu.upb.lp.isc.pR.Expresion;
import edu.upb.lp.isc.pR.PRPackage;
import edu.upb.lp.isc.pR.Programa;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Programa</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.pR.impl.ProgramaImpl#getName <em>Name</em>}</li>
 *   <li>{@link edu.upb.lp.isc.pR.impl.ProgramaImpl#getDefiniciones <em>Definiciones</em>}</li>
 *   <li>{@link edu.upb.lp.isc.pR.impl.ProgramaImpl#getEjecuciones <em>Ejecuciones</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ProgramaImpl extends MinimalEObjectImpl.Container implements Programa
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getDefiniciones() <em>Definiciones</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefiniciones()
   * @generated
   * @ordered
   */
  protected EList<Definicion> definiciones;

  /**
   * The cached value of the '{@link #getEjecuciones() <em>Ejecuciones</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEjecuciones()
   * @generated
   * @ordered
   */
  protected EList<Expresion> ejecuciones;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProgramaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PRPackage.Literals.PROGRAMA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PRPackage.PROGRAMA__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Definicion> getDefiniciones()
  {
    if (definiciones == null)
    {
      definiciones = new EObjectContainmentEList<Definicion>(Definicion.class, this, PRPackage.PROGRAMA__DEFINICIONES);
    }
    return definiciones;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Expresion> getEjecuciones()
  {
    if (ejecuciones == null)
    {
      ejecuciones = new EObjectContainmentEList<Expresion>(Expresion.class, this, PRPackage.PROGRAMA__EJECUCIONES);
    }
    return ejecuciones;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PRPackage.PROGRAMA__DEFINICIONES:
        return ((InternalEList<?>)getDefiniciones()).basicRemove(otherEnd, msgs);
      case PRPackage.PROGRAMA__EJECUCIONES:
        return ((InternalEList<?>)getEjecuciones()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PRPackage.PROGRAMA__NAME:
        return getName();
      case PRPackage.PROGRAMA__DEFINICIONES:
        return getDefiniciones();
      case PRPackage.PROGRAMA__EJECUCIONES:
        return getEjecuciones();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PRPackage.PROGRAMA__NAME:
        setName((String)newValue);
        return;
      case PRPackage.PROGRAMA__DEFINICIONES:
        getDefiniciones().clear();
        getDefiniciones().addAll((Collection<? extends Definicion>)newValue);
        return;
      case PRPackage.PROGRAMA__EJECUCIONES:
        getEjecuciones().clear();
        getEjecuciones().addAll((Collection<? extends Expresion>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PRPackage.PROGRAMA__NAME:
        setName(NAME_EDEFAULT);
        return;
      case PRPackage.PROGRAMA__DEFINICIONES:
        getDefiniciones().clear();
        return;
      case PRPackage.PROGRAMA__EJECUCIONES:
        getEjecuciones().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PRPackage.PROGRAMA__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case PRPackage.PROGRAMA__DEFINICIONES:
        return definiciones != null && !definiciones.isEmpty();
      case PRPackage.PROGRAMA__EJECUCIONES:
        return ejecuciones != null && !ejecuciones.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //ProgramaImpl
