/*
 * generated by Xtext 2.12.0
 */
package edu.upb.lp.isc.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPRScopeProvider extends DelegatingScopeProvider {
}
