/**
 * generated by Xtext 2.12.0
 */
package edu.upb.lp.isc.validation;

import edu.upb.lp.isc.validation.AbstractPRValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class PRValidator extends AbstractPRValidator {
}
