/*
 * generated by Xtext 2.12.0
 */
package edu.upb.lp.isc.validation

import edu.upb.lp.isc.pR.PRPackage
import edu.upb.lp.isc.pR.Programa
import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class PRValidator extends AbstractPRValidator {
	
//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					PRPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}

	@Check
	def programHasMoreThan3Definitions(Programa pr) {
		if (pr.definiciones.length < 3) {
			error("Malo malo", PRPackage.Literals.PROGRAMA__DEFINICIONES)
		} 
	}
	
}
