/**
 * generated by Xtext 2.12.0
 */
package edu.upb.lp.isc.scoping;

import edu.upb.lp.isc.scoping.AbstractPRScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class PRScopeProvider extends AbstractPRScopeProvider {
}
