/*
 * generated by Xtext 2.12.0
 */
package edu.upb.lp.isc


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PRStandaloneSetup extends PRStandaloneSetupGenerated {

	def static void doSetup() {
		new PRStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
