/**
 * generated by Xtext 2.12.0
 */
package edu.upb.lp.isc;

import edu.upb.lp.isc.PRStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class PRStandaloneSetup extends PRStandaloneSetupGenerated {
  public static void doSetup() {
    new PRStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
