/**
 * generated by Xtext 2.12.0
 */
package edu.upb.lp.isc.pR;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Accion</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.pR.Accion#getOperador <em>Operador</em>}</li>
 *   <li>{@link edu.upb.lp.isc.pR.Accion#getObjeto1 <em>Objeto1</em>}</li>
 *   <li>{@link edu.upb.lp.isc.pR.Accion#getObjeto2 <em>Objeto2</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.pR.PRPackage#getAccion()
 * @model
 * @generated
 */
public interface Accion extends EObject
{
  /**
   * Returns the value of the '<em><b>Operador</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Operador</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operador</em>' attribute.
   * @see #setOperador(String)
   * @see edu.upb.lp.isc.pR.PRPackage#getAccion_Operador()
   * @model
   * @generated
   */
  String getOperador();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.pR.Accion#getOperador <em>Operador</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operador</em>' attribute.
   * @see #getOperador()
   * @generated
   */
  void setOperador(String value);

  /**
   * Returns the value of the '<em><b>Objeto1</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Objeto1</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objeto1</em>' reference.
   * @see #setObjeto1(Variable)
   * @see edu.upb.lp.isc.pR.PRPackage#getAccion_Objeto1()
   * @model
   * @generated
   */
  Variable getObjeto1();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.pR.Accion#getObjeto1 <em>Objeto1</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Objeto1</em>' reference.
   * @see #getObjeto1()
   * @generated
   */
  void setObjeto1(Variable value);

  /**
   * Returns the value of the '<em><b>Objeto2</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Objeto2</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objeto2</em>' reference.
   * @see #setObjeto2(Variable)
   * @see edu.upb.lp.isc.pR.PRPackage#getAccion_Objeto2()
   * @model
   * @generated
   */
  Variable getObjeto2();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.pR.Accion#getObjeto2 <em>Objeto2</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Objeto2</em>' reference.
   * @see #getObjeto2()
   * @generated
   */
  void setObjeto2(Variable value);

} // Accion
