/**
 * generated by Xtext 2.12.0
 */
package edu.upb.lp.isc.pR;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Funcion</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.pR.Funcion#getName <em>Name</em>}</li>
 *   <li>{@link edu.upb.lp.isc.pR.Funcion#getVariable <em>Variable</em>}</li>
 *   <li>{@link edu.upb.lp.isc.pR.Funcion#getAcciones <em>Acciones</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.pR.PRPackage#getFuncion()
 * @model
 * @generated
 */
public interface Funcion extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see edu.upb.lp.isc.pR.PRPackage#getFuncion_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.pR.Funcion#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Variable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Variable</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable</em>' reference.
   * @see #setVariable(Variable)
   * @see edu.upb.lp.isc.pR.PRPackage#getFuncion_Variable()
   * @model
   * @generated
   */
  Variable getVariable();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.pR.Funcion#getVariable <em>Variable</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable</em>' reference.
   * @see #getVariable()
   * @generated
   */
  void setVariable(Variable value);

  /**
   * Returns the value of the '<em><b>Acciones</b></em>' containment reference list.
   * The list contents are of type {@link edu.upb.lp.isc.pR.Accion}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Acciones</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Acciones</em>' containment reference list.
   * @see edu.upb.lp.isc.pR.PRPackage#getFuncion_Acciones()
   * @model containment="true"
   * @generated
   */
  EList<Accion> getAcciones();

} // Funcion
