/**
 * generated by Xtext 2.12.0
 */
package edu.upb.lp.isc.pR;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Programa</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.pR.Programa#getVariables <em>Variables</em>}</li>
 *   <li>{@link edu.upb.lp.isc.pR.Programa#getExpresiones <em>Expresiones</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.pR.PRPackage#getPrograma()
 * @model
 * @generated
 */
public interface Programa extends EObject
{
  /**
   * Returns the value of the '<em><b>Variables</b></em>' containment reference list.
   * The list contents are of type {@link edu.upb.lp.isc.pR.Variable}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Variables</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variables</em>' containment reference list.
   * @see edu.upb.lp.isc.pR.PRPackage#getPrograma_Variables()
   * @model containment="true"
   * @generated
   */
  EList<Variable> getVariables();

  /**
   * Returns the value of the '<em><b>Expresiones</b></em>' containment reference list.
   * The list contents are of type {@link edu.upb.lp.isc.pR.Expresion}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expresiones</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expresiones</em>' containment reference list.
   * @see edu.upb.lp.isc.pR.PRPackage#getPrograma_Expresiones()
   * @model containment="true"
   * @generated
   */
  EList<Expresion> getExpresiones();

} // Programa
