/**
 * generated by Xtext 2.12.0
 */
package edu.upb.lp.isc.pR;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see edu.upb.lp.isc.pR.PRFactory
 * @model kind="package"
 * @generated
 */
public interface PRPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "pR";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.upb.edu/lp/isc/PR";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "pR";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PRPackage eINSTANCE = edu.upb.lp.isc.pR.impl.PRPackageImpl.init();

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.pR.impl.ProgramaImpl <em>Programa</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.pR.impl.ProgramaImpl
   * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getPrograma()
   * @generated
   */
  int PROGRAMA = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMA__NAME = 0;

  /**
   * The feature id for the '<em><b>Variables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMA__VARIABLES = 1;

  /**
   * The feature id for the '<em><b>Definiciones</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMA__DEFINICIONES = 2;

  /**
   * The feature id for the '<em><b>Ejecuciones</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMA__EJECUCIONES = 3;

  /**
   * The number of structural features of the '<em>Programa</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMA_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.pR.impl.VariableImpl <em>Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.pR.impl.VariableImpl
   * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getVariable()
   * @generated
   */
  int VARIABLE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__VALUE = 1;

  /**
   * The number of structural features of the '<em>Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.pR.impl.DefinicionImpl <em>Definicion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.pR.impl.DefinicionImpl
   * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getDefinicion()
   * @generated
   */
  int DEFINICION = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINICION__NAME = 0;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINICION__ARGS = 1;

  /**
   * The feature id for the '<em><b>Operador</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINICION__OPERADOR = 2;

  /**
   * The feature id for the '<em><b>Valores</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINICION__VALORES = 3;

  /**
   * The number of structural features of the '<em>Definicion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINICION_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.pR.impl.ValueImpl <em>Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.pR.impl.ValueImpl
   * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getValue()
   * @generated
   */
  int VALUE = 3;

  /**
   * The number of structural features of the '<em>Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.pR.impl.RefValueImpl <em>Ref Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.pR.impl.RefValueImpl
   * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getRefValue()
   * @generated
   */
  int REF_VALUE = 4;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REF_VALUE__REF = VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Ref Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REF_VALUE_FEATURE_COUNT = VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.pR.impl.StringValueImpl <em>String Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.pR.impl.StringValueImpl
   * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getStringValue()
   * @generated
   */
  int STRING_VALUE = 5;

  /**
   * The feature id for the '<em><b>Str</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_VALUE__STR = VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>String Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_VALUE_FEATURE_COUNT = VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.pR.impl.IntValueImpl <em>Int Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.pR.impl.IntValueImpl
   * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getIntValue()
   * @generated
   */
  int INT_VALUE = 6;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_VALUE__VAL = VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_VALUE_FEATURE_COUNT = VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.pR.impl.ArgumentoImpl <em>Argumento</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.pR.impl.ArgumentoImpl
   * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getArgumento()
   * @generated
   */
  int ARGUMENTO = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARGUMENTO__NAME = 0;

  /**
   * The number of structural features of the '<em>Argumento</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARGUMENTO_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.pR.impl.ExpresionImpl <em>Expresion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.pR.impl.ExpresionImpl
   * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getExpresion()
   * @generated
   */
  int EXPRESION = 8;

  /**
   * The feature id for the '<em><b>Definiciones</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESION__DEFINICIONES = 0;

  /**
   * The feature id for the '<em><b>Parametros</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESION__PARAMETROS = 1;

  /**
   * The number of structural features of the '<em>Expresion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESION_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.pR.Programa <em>Programa</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Programa</em>'.
   * @see edu.upb.lp.isc.pR.Programa
   * @generated
   */
  EClass getPrograma();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.pR.Programa#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.upb.lp.isc.pR.Programa#getName()
   * @see #getPrograma()
   * @generated
   */
  EAttribute getPrograma_Name();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.pR.Programa#getVariables <em>Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Variables</em>'.
   * @see edu.upb.lp.isc.pR.Programa#getVariables()
   * @see #getPrograma()
   * @generated
   */
  EReference getPrograma_Variables();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.pR.Programa#getDefiniciones <em>Definiciones</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Definiciones</em>'.
   * @see edu.upb.lp.isc.pR.Programa#getDefiniciones()
   * @see #getPrograma()
   * @generated
   */
  EReference getPrograma_Definiciones();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.pR.Programa#getEjecuciones <em>Ejecuciones</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Ejecuciones</em>'.
   * @see edu.upb.lp.isc.pR.Programa#getEjecuciones()
   * @see #getPrograma()
   * @generated
   */
  EReference getPrograma_Ejecuciones();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.pR.Variable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable</em>'.
   * @see edu.upb.lp.isc.pR.Variable
   * @generated
   */
  EClass getVariable();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.pR.Variable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.upb.lp.isc.pR.Variable#getName()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Name();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.pR.Variable#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see edu.upb.lp.isc.pR.Variable#getValue()
   * @see #getVariable()
   * @generated
   */
  EReference getVariable_Value();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.pR.Definicion <em>Definicion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Definicion</em>'.
   * @see edu.upb.lp.isc.pR.Definicion
   * @generated
   */
  EClass getDefinicion();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.pR.Definicion#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.upb.lp.isc.pR.Definicion#getName()
   * @see #getDefinicion()
   * @generated
   */
  EAttribute getDefinicion_Name();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.pR.Definicion#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Args</em>'.
   * @see edu.upb.lp.isc.pR.Definicion#getArgs()
   * @see #getDefinicion()
   * @generated
   */
  EReference getDefinicion_Args();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.pR.Definicion#getOperador <em>Operador</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operador</em>'.
   * @see edu.upb.lp.isc.pR.Definicion#getOperador()
   * @see #getDefinicion()
   * @generated
   */
  EAttribute getDefinicion_Operador();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.pR.Definicion#getValores <em>Valores</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Valores</em>'.
   * @see edu.upb.lp.isc.pR.Definicion#getValores()
   * @see #getDefinicion()
   * @generated
   */
  EReference getDefinicion_Valores();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.pR.Value <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Value</em>'.
   * @see edu.upb.lp.isc.pR.Value
   * @generated
   */
  EClass getValue();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.pR.RefValue <em>Ref Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ref Value</em>'.
   * @see edu.upb.lp.isc.pR.RefValue
   * @generated
   */
  EClass getRefValue();

  /**
   * Returns the meta object for the reference '{@link edu.upb.lp.isc.pR.RefValue#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see edu.upb.lp.isc.pR.RefValue#getRef()
   * @see #getRefValue()
   * @generated
   */
  EReference getRefValue_Ref();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.pR.StringValue <em>String Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Value</em>'.
   * @see edu.upb.lp.isc.pR.StringValue
   * @generated
   */
  EClass getStringValue();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.pR.StringValue#getStr <em>Str</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Str</em>'.
   * @see edu.upb.lp.isc.pR.StringValue#getStr()
   * @see #getStringValue()
   * @generated
   */
  EAttribute getStringValue_Str();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.pR.IntValue <em>Int Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Value</em>'.
   * @see edu.upb.lp.isc.pR.IntValue
   * @generated
   */
  EClass getIntValue();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.pR.IntValue#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see edu.upb.lp.isc.pR.IntValue#getVal()
   * @see #getIntValue()
   * @generated
   */
  EAttribute getIntValue_Val();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.pR.Argumento <em>Argumento</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Argumento</em>'.
   * @see edu.upb.lp.isc.pR.Argumento
   * @generated
   */
  EClass getArgumento();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.pR.Argumento#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.upb.lp.isc.pR.Argumento#getName()
   * @see #getArgumento()
   * @generated
   */
  EAttribute getArgumento_Name();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.pR.Expresion <em>Expresion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expresion</em>'.
   * @see edu.upb.lp.isc.pR.Expresion
   * @generated
   */
  EClass getExpresion();

  /**
   * Returns the meta object for the reference list '{@link edu.upb.lp.isc.pR.Expresion#getDefiniciones <em>Definiciones</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Definiciones</em>'.
   * @see edu.upb.lp.isc.pR.Expresion#getDefiniciones()
   * @see #getExpresion()
   * @generated
   */
  EReference getExpresion_Definiciones();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.pR.Expresion#getParametros <em>Parametros</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parametros</em>'.
   * @see edu.upb.lp.isc.pR.Expresion#getParametros()
   * @see #getExpresion()
   * @generated
   */
  EReference getExpresion_Parametros();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  PRFactory getPRFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.pR.impl.ProgramaImpl <em>Programa</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.pR.impl.ProgramaImpl
     * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getPrograma()
     * @generated
     */
    EClass PROGRAMA = eINSTANCE.getPrograma();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROGRAMA__NAME = eINSTANCE.getPrograma_Name();

    /**
     * The meta object literal for the '<em><b>Variables</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAMA__VARIABLES = eINSTANCE.getPrograma_Variables();

    /**
     * The meta object literal for the '<em><b>Definiciones</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAMA__DEFINICIONES = eINSTANCE.getPrograma_Definiciones();

    /**
     * The meta object literal for the '<em><b>Ejecuciones</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAMA__EJECUCIONES = eINSTANCE.getPrograma_Ejecuciones();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.pR.impl.VariableImpl <em>Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.pR.impl.VariableImpl
     * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getVariable()
     * @generated
     */
    EClass VARIABLE = eINSTANCE.getVariable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__NAME = eINSTANCE.getVariable_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLE__VALUE = eINSTANCE.getVariable_Value();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.pR.impl.DefinicionImpl <em>Definicion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.pR.impl.DefinicionImpl
     * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getDefinicion()
     * @generated
     */
    EClass DEFINICION = eINSTANCE.getDefinicion();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEFINICION__NAME = eINSTANCE.getDefinicion_Name();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFINICION__ARGS = eINSTANCE.getDefinicion_Args();

    /**
     * The meta object literal for the '<em><b>Operador</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEFINICION__OPERADOR = eINSTANCE.getDefinicion_Operador();

    /**
     * The meta object literal for the '<em><b>Valores</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFINICION__VALORES = eINSTANCE.getDefinicion_Valores();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.pR.impl.ValueImpl <em>Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.pR.impl.ValueImpl
     * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getValue()
     * @generated
     */
    EClass VALUE = eINSTANCE.getValue();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.pR.impl.RefValueImpl <em>Ref Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.pR.impl.RefValueImpl
     * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getRefValue()
     * @generated
     */
    EClass REF_VALUE = eINSTANCE.getRefValue();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REF_VALUE__REF = eINSTANCE.getRefValue_Ref();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.pR.impl.StringValueImpl <em>String Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.pR.impl.StringValueImpl
     * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getStringValue()
     * @generated
     */
    EClass STRING_VALUE = eINSTANCE.getStringValue();

    /**
     * The meta object literal for the '<em><b>Str</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_VALUE__STR = eINSTANCE.getStringValue_Str();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.pR.impl.IntValueImpl <em>Int Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.pR.impl.IntValueImpl
     * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getIntValue()
     * @generated
     */
    EClass INT_VALUE = eINSTANCE.getIntValue();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_VALUE__VAL = eINSTANCE.getIntValue_Val();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.pR.impl.ArgumentoImpl <em>Argumento</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.pR.impl.ArgumentoImpl
     * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getArgumento()
     * @generated
     */
    EClass ARGUMENTO = eINSTANCE.getArgumento();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARGUMENTO__NAME = eINSTANCE.getArgumento_Name();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.pR.impl.ExpresionImpl <em>Expresion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.pR.impl.ExpresionImpl
     * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getExpresion()
     * @generated
     */
    EClass EXPRESION = eINSTANCE.getExpresion();

    /**
     * The meta object literal for the '<em><b>Definiciones</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESION__DEFINICIONES = eINSTANCE.getExpresion_Definiciones();

    /**
     * The meta object literal for the '<em><b>Parametros</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESION__PARAMETROS = eINSTANCE.getExpresion_Parametros();

  }

} //PRPackage
