/**
 * generated by Xtext 2.12.0
 */
package edu.upb.lp.isc.pR;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see edu.upb.lp.isc.pR.PRFactory
 * @model kind="package"
 * @generated
 */
public interface PRPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "pR";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.upb.edu/lp/isc/PR";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "pR";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PRPackage eINSTANCE = edu.upb.lp.isc.pR.impl.PRPackageImpl.init();

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.pR.impl.ProgramaImpl <em>Programa</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.pR.impl.ProgramaImpl
   * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getPrograma()
   * @generated
   */
  int PROGRAMA = 0;

  /**
   * The feature id for the '<em><b>Variables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMA__VARIABLES = 0;

  /**
   * The feature id for the '<em><b>Expresiones</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMA__EXPRESIONES = 1;

  /**
   * The number of structural features of the '<em>Programa</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMA_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.pR.impl.VariableImpl <em>Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.pR.impl.VariableImpl
   * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getVariable()
   * @generated
   */
  int VARIABLE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__VALUE = 1;

  /**
   * The number of structural features of the '<em>Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.pR.impl.ExpresionImpl <em>Expresion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.pR.impl.ExpresionImpl
   * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getExpresion()
   * @generated
   */
  int EXPRESION = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESION__NAME = 0;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESION__ARGS = 1;

  /**
   * The feature id for the '<em><b>Operador</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESION__OPERADOR = 2;

  /**
   * The feature id for the '<em><b>Value1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESION__VALUE1 = 3;

  /**
   * The feature id for the '<em><b>Value2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESION__VALUE2 = 4;

  /**
   * The number of structural features of the '<em>Expresion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESION_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.pR.impl.ValueImpl <em>Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.pR.impl.ValueImpl
   * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getValue()
   * @generated
   */
  int VALUE = 3;

  /**
   * The number of structural features of the '<em>Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.pR.impl.RefValueImpl <em>Ref Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.pR.impl.RefValueImpl
   * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getRefValue()
   * @generated
   */
  int REF_VALUE = 4;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REF_VALUE__REF = VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Ref Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REF_VALUE_FEATURE_COUNT = VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.pR.impl.StringValueImpl <em>String Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.pR.impl.StringValueImpl
   * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getStringValue()
   * @generated
   */
  int STRING_VALUE = 5;

  /**
   * The feature id for the '<em><b>Str</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_VALUE__STR = VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>String Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_VALUE_FEATURE_COUNT = VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.pR.impl.IntValueImpl <em>Int Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.pR.impl.IntValueImpl
   * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getIntValue()
   * @generated
   */
  int INT_VALUE = 6;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_VALUE__VAL = VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_VALUE_FEATURE_COUNT = VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.pR.impl.ArgumentoImpl <em>Argumento</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.pR.impl.ArgumentoImpl
   * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getArgumento()
   * @generated
   */
  int ARGUMENTO = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARGUMENTO__NAME = 0;

  /**
   * The number of structural features of the '<em>Argumento</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARGUMENTO_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.pR.impl.FuncionImpl <em>Funcion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.pR.impl.FuncionImpl
   * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getFuncion()
   * @generated
   */
  int FUNCION = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCION__NAME = 0;

  /**
   * The feature id for the '<em><b>Variable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCION__VARIABLE = 1;

  /**
   * The feature id for the '<em><b>Acciones</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCION__ACCIONES = 2;

  /**
   * The number of structural features of the '<em>Funcion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.pR.impl.AccionImpl <em>Accion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.pR.impl.AccionImpl
   * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getAccion()
   * @generated
   */
  int ACCION = 9;

  /**
   * The feature id for the '<em><b>Operador</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACCION__OPERADOR = 0;

  /**
   * The feature id for the '<em><b>Objeto1</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACCION__OBJETO1 = 1;

  /**
   * The feature id for the '<em><b>Objeto2</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACCION__OBJETO2 = 2;

  /**
   * The number of structural features of the '<em>Accion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACCION_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.pR.Programa <em>Programa</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Programa</em>'.
   * @see edu.upb.lp.isc.pR.Programa
   * @generated
   */
  EClass getPrograma();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.pR.Programa#getVariables <em>Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Variables</em>'.
   * @see edu.upb.lp.isc.pR.Programa#getVariables()
   * @see #getPrograma()
   * @generated
   */
  EReference getPrograma_Variables();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.pR.Programa#getExpresiones <em>Expresiones</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expresiones</em>'.
   * @see edu.upb.lp.isc.pR.Programa#getExpresiones()
   * @see #getPrograma()
   * @generated
   */
  EReference getPrograma_Expresiones();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.pR.Variable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable</em>'.
   * @see edu.upb.lp.isc.pR.Variable
   * @generated
   */
  EClass getVariable();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.pR.Variable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.upb.lp.isc.pR.Variable#getName()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Name();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.pR.Variable#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see edu.upb.lp.isc.pR.Variable#getValue()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Value();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.pR.Expresion <em>Expresion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expresion</em>'.
   * @see edu.upb.lp.isc.pR.Expresion
   * @generated
   */
  EClass getExpresion();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.pR.Expresion#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.upb.lp.isc.pR.Expresion#getName()
   * @see #getExpresion()
   * @generated
   */
  EAttribute getExpresion_Name();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.pR.Expresion#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Args</em>'.
   * @see edu.upb.lp.isc.pR.Expresion#getArgs()
   * @see #getExpresion()
   * @generated
   */
  EReference getExpresion_Args();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.pR.Expresion#getOperador <em>Operador</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operador</em>'.
   * @see edu.upb.lp.isc.pR.Expresion#getOperador()
   * @see #getExpresion()
   * @generated
   */
  EAttribute getExpresion_Operador();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.pR.Expresion#getValue1 <em>Value1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value1</em>'.
   * @see edu.upb.lp.isc.pR.Expresion#getValue1()
   * @see #getExpresion()
   * @generated
   */
  EReference getExpresion_Value1();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.pR.Expresion#getValue2 <em>Value2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value2</em>'.
   * @see edu.upb.lp.isc.pR.Expresion#getValue2()
   * @see #getExpresion()
   * @generated
   */
  EReference getExpresion_Value2();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.pR.Value <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Value</em>'.
   * @see edu.upb.lp.isc.pR.Value
   * @generated
   */
  EClass getValue();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.pR.RefValue <em>Ref Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ref Value</em>'.
   * @see edu.upb.lp.isc.pR.RefValue
   * @generated
   */
  EClass getRefValue();

  /**
   * Returns the meta object for the reference '{@link edu.upb.lp.isc.pR.RefValue#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see edu.upb.lp.isc.pR.RefValue#getRef()
   * @see #getRefValue()
   * @generated
   */
  EReference getRefValue_Ref();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.pR.StringValue <em>String Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Value</em>'.
   * @see edu.upb.lp.isc.pR.StringValue
   * @generated
   */
  EClass getStringValue();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.pR.StringValue#getStr <em>Str</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Str</em>'.
   * @see edu.upb.lp.isc.pR.StringValue#getStr()
   * @see #getStringValue()
   * @generated
   */
  EAttribute getStringValue_Str();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.pR.IntValue <em>Int Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Value</em>'.
   * @see edu.upb.lp.isc.pR.IntValue
   * @generated
   */
  EClass getIntValue();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.pR.IntValue#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see edu.upb.lp.isc.pR.IntValue#getVal()
   * @see #getIntValue()
   * @generated
   */
  EAttribute getIntValue_Val();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.pR.Argumento <em>Argumento</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Argumento</em>'.
   * @see edu.upb.lp.isc.pR.Argumento
   * @generated
   */
  EClass getArgumento();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.pR.Argumento#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.upb.lp.isc.pR.Argumento#getName()
   * @see #getArgumento()
   * @generated
   */
  EAttribute getArgumento_Name();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.pR.Funcion <em>Funcion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Funcion</em>'.
   * @see edu.upb.lp.isc.pR.Funcion
   * @generated
   */
  EClass getFuncion();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.pR.Funcion#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.upb.lp.isc.pR.Funcion#getName()
   * @see #getFuncion()
   * @generated
   */
  EAttribute getFuncion_Name();

  /**
   * Returns the meta object for the reference '{@link edu.upb.lp.isc.pR.Funcion#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Variable</em>'.
   * @see edu.upb.lp.isc.pR.Funcion#getVariable()
   * @see #getFuncion()
   * @generated
   */
  EReference getFuncion_Variable();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.pR.Funcion#getAcciones <em>Acciones</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Acciones</em>'.
   * @see edu.upb.lp.isc.pR.Funcion#getAcciones()
   * @see #getFuncion()
   * @generated
   */
  EReference getFuncion_Acciones();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.pR.Accion <em>Accion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Accion</em>'.
   * @see edu.upb.lp.isc.pR.Accion
   * @generated
   */
  EClass getAccion();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.pR.Accion#getOperador <em>Operador</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operador</em>'.
   * @see edu.upb.lp.isc.pR.Accion#getOperador()
   * @see #getAccion()
   * @generated
   */
  EAttribute getAccion_Operador();

  /**
   * Returns the meta object for the reference '{@link edu.upb.lp.isc.pR.Accion#getObjeto1 <em>Objeto1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Objeto1</em>'.
   * @see edu.upb.lp.isc.pR.Accion#getObjeto1()
   * @see #getAccion()
   * @generated
   */
  EReference getAccion_Objeto1();

  /**
   * Returns the meta object for the reference '{@link edu.upb.lp.isc.pR.Accion#getObjeto2 <em>Objeto2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Objeto2</em>'.
   * @see edu.upb.lp.isc.pR.Accion#getObjeto2()
   * @see #getAccion()
   * @generated
   */
  EReference getAccion_Objeto2();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  PRFactory getPRFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.pR.impl.ProgramaImpl <em>Programa</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.pR.impl.ProgramaImpl
     * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getPrograma()
     * @generated
     */
    EClass PROGRAMA = eINSTANCE.getPrograma();

    /**
     * The meta object literal for the '<em><b>Variables</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAMA__VARIABLES = eINSTANCE.getPrograma_Variables();

    /**
     * The meta object literal for the '<em><b>Expresiones</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAMA__EXPRESIONES = eINSTANCE.getPrograma_Expresiones();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.pR.impl.VariableImpl <em>Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.pR.impl.VariableImpl
     * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getVariable()
     * @generated
     */
    EClass VARIABLE = eINSTANCE.getVariable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__NAME = eINSTANCE.getVariable_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__VALUE = eINSTANCE.getVariable_Value();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.pR.impl.ExpresionImpl <em>Expresion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.pR.impl.ExpresionImpl
     * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getExpresion()
     * @generated
     */
    EClass EXPRESION = eINSTANCE.getExpresion();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESION__NAME = eINSTANCE.getExpresion_Name();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESION__ARGS = eINSTANCE.getExpresion_Args();

    /**
     * The meta object literal for the '<em><b>Operador</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESION__OPERADOR = eINSTANCE.getExpresion_Operador();

    /**
     * The meta object literal for the '<em><b>Value1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESION__VALUE1 = eINSTANCE.getExpresion_Value1();

    /**
     * The meta object literal for the '<em><b>Value2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESION__VALUE2 = eINSTANCE.getExpresion_Value2();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.pR.impl.ValueImpl <em>Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.pR.impl.ValueImpl
     * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getValue()
     * @generated
     */
    EClass VALUE = eINSTANCE.getValue();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.pR.impl.RefValueImpl <em>Ref Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.pR.impl.RefValueImpl
     * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getRefValue()
     * @generated
     */
    EClass REF_VALUE = eINSTANCE.getRefValue();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REF_VALUE__REF = eINSTANCE.getRefValue_Ref();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.pR.impl.StringValueImpl <em>String Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.pR.impl.StringValueImpl
     * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getStringValue()
     * @generated
     */
    EClass STRING_VALUE = eINSTANCE.getStringValue();

    /**
     * The meta object literal for the '<em><b>Str</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_VALUE__STR = eINSTANCE.getStringValue_Str();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.pR.impl.IntValueImpl <em>Int Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.pR.impl.IntValueImpl
     * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getIntValue()
     * @generated
     */
    EClass INT_VALUE = eINSTANCE.getIntValue();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_VALUE__VAL = eINSTANCE.getIntValue_Val();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.pR.impl.ArgumentoImpl <em>Argumento</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.pR.impl.ArgumentoImpl
     * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getArgumento()
     * @generated
     */
    EClass ARGUMENTO = eINSTANCE.getArgumento();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARGUMENTO__NAME = eINSTANCE.getArgumento_Name();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.pR.impl.FuncionImpl <em>Funcion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.pR.impl.FuncionImpl
     * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getFuncion()
     * @generated
     */
    EClass FUNCION = eINSTANCE.getFuncion();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCION__NAME = eINSTANCE.getFuncion_Name();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCION__VARIABLE = eINSTANCE.getFuncion_Variable();

    /**
     * The meta object literal for the '<em><b>Acciones</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCION__ACCIONES = eINSTANCE.getFuncion_Acciones();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.pR.impl.AccionImpl <em>Accion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.pR.impl.AccionImpl
     * @see edu.upb.lp.isc.pR.impl.PRPackageImpl#getAccion()
     * @generated
     */
    EClass ACCION = eINSTANCE.getAccion();

    /**
     * The meta object literal for the '<em><b>Operador</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACCION__OPERADOR = eINSTANCE.getAccion_Operador();

    /**
     * The meta object literal for the '<em><b>Objeto1</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACCION__OBJETO1 = eINSTANCE.getAccion_Objeto1();

    /**
     * The meta object literal for the '<em><b>Objeto2</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACCION__OBJETO2 = eINSTANCE.getAccion_Objeto2();

  }

} //PRPackage
