/**
 * generated by Xtext 2.12.0
 */
package edu.upb.lp.isc.pR;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ref Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.pR.RefValue#getRef <em>Ref</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.pR.PRPackage#getRefValue()
 * @model
 * @generated
 */
public interface RefValue extends Value
{
  /**
   * Returns the value of the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ref</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' reference.
   * @see #setRef(Argumento)
   * @see edu.upb.lp.isc.pR.PRPackage#getRefValue_Ref()
   * @model
   * @generated
   */
  Argumento getRef();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.pR.RefValue#getRef <em>Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' reference.
   * @see #getRef()
   * @generated
   */
  void setRef(Argumento value);

} // RefValue
